name             'zip_proxy'
maintainer       'Justin Alan Ryan (ZipRealty / Realogy)'
maintainer_email 'juryan@ziprealty.com'
license          'Apache 2.0'
description      'Installs/Configures zip_proxy'
long_description 'Installs/Configures zip_proxy'
version          '0.1.0'
